=== naota-inamoto/Altair/sample/server/dtd/rosetta/PipInfo.dtd
<!ELEMENT PipInfo (Target, Id, Message*)>

<!ELEMENT Target (#PCDATA)>
<!ELEMENT Id (#PCDATA)>

<!ELEMENT Message (MsgType, MessageVersion, DTDfilename, MessageCode,
    FromRoleClass, FromService, ToRoleClass, ToService, TransactionCode, NextAction,
    Indicator, ProcessCode, ProcessVersion)>

<!ELEMENT MsgType (#PCDATA)>
<!ELEMENT MessageVersion (#PCDATA)>
<!ELEMENT DTDfilename (#PCDATA)>
<!ELEMENT MessageCode (#PCDATA)>

<!ELEMENT FromRoleClass (#PCDATA)>
<!ELEMENT FromService (#PCDATA)>
<!ELEMENT ToRoleClass (#PCDATA)>
<!ELEMENT ToService (#PCDATA)>
<!ELEMENT TransactionCode (#PCDATA)>
<!ELEMENT NextAction (#PCDATA)>

<!ELEMENT Indicator (#PCDATA)>
<!ELEMENT ProcessCode (#PCDATA)>
<!ELEMENT ProcessVersion (#PCDATA)>

=== naota-inamoto/Altair/sample/server/data/rosetta/init_pip_default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PipInfo SYSTEM "PipInfo.dtd">
<PipInfo>
    <Target>rosetta</Target>
    <Id>message type</Id>

    <!-- RNIF 2.0 -->
    <Message>
        <MsgType>Preamble</MsgType>
        <MessageVersion>V02.00</MessageVersion>
        <DTDfilename>rosetta/Preamble_MS_V02_00.dtd</DTDfilename>
        <MessageCode>Preamble</MessageCode>
        <FromRoleClass></FromRoleClass>
        <FromService></FromService>
        <ToRoleClass></ToRoleClass>
        <ToService></ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator></Indicator>
        <ProcessCode></ProcessCode>
        <ProcessVersion></ProcessVersion>
    </Message>
    <Message>
        <MsgType>DeliveryHeader</MsgType>
        <MessageVersion>V02.00</MessageVersion>
        <DTDfilename>rosetta/DeliveryHeader_MS_V02_00.dtd</DTDfilename>
        <MessageCode>DeliveryHeader</MessageCode>
        <FromRoleClass></FromRoleClass>
        <FromService></FromService>
        <ToRoleClass></ToRoleClass>
        <ToService></ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator></Indicator>
        <ProcessCode></ProcessCode>
        <ProcessVersion></ProcessVersion>
    </Message>
    <Message>
        <MsgType>ServiceHeader</MsgType>
        <MessageVersion>V02.00</MessageVersion>
        <DTDfilename>rosetta/ServiceHeader_MS_V02_00.dtd</DTDfilename>
        <MessageCode>ServiceHeader</MessageCode>
        <FromRoleClass></FromRoleClass>
        <FromService></FromService>
        <ToRoleClass></ToRoleClass>
        <ToService></ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator></Indicator>
        <ProcessCode></ProcessCode>
        <ProcessVersion></ProcessVersion>
    </Message>
    <Message>
        <MsgType>ReceiptAcknowledgment</MsgType>
        <MessageVersion>V02.00</MessageVersion>
        <DTDfilename>rosetta/AcknowledgmentOfReceipt_MS_V02_00.dtd</DTDfilename>
        <MessageCode>Receipt Acknowledgment</MessageCode>
        <FromRoleClass></FromRoleClass>
        <FromService></FromService>
        <ToRoleClass></ToRoleClass>
        <ToService></ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator></Indicator>
        <ProcessCode></ProcessCode>
        <ProcessVersion></ProcessVersion>
    </Message>
    <Message>
        <MsgType>Exception</MsgType>
        <MessageVersion>V02.00</MessageVersion>
        <DTDfilename>rosetta/Exception_MS_V02_00.dtd</DTDfilename>
        <MessageCode>Exception</MessageCode>
        <FromRoleClass></FromRoleClass>
        <FromService></FromService>
        <ToRoleClass></ToRoleClass>
        <ToService></ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator></Indicator>
        <ProcessCode></ProcessCode>
        <ProcessVersion></ProcessVersion>
    </Message>

    <!-- 0A1 Failure Notification 1.0 -->
    <Message>
        <MsgType>Pip0A1FailureNotification</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/0A1FailureNotificationMessageGuideline.dtd</DTDfilename>
        <MessageCode>Failure Notification Action</MessageCode>
        <FromRoleClass>PIP Failure Notifier</FromRoleClass>
        <FromService>Failure Notifier Service</FromService>
        <ToRoleClass>Failure Report Administrator</ToRoleClass>
        <ToService>Failure Report Administrator Service</ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator>0A1</Indicator>
        <ProcessCode>Notification of Failure</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>
    <!-- 0A1 Failure Notification V02.00 -->
    <Message>
        <MsgType>Pip0A1FailureNotification</MsgType>
        <MessageVersion>V02.00</MessageVersion>
        <DTDfilename>rosetta/0A1_MS_V02_00_FailureNotification.dtd</DTDfilename>
        <MessageCode>Failure Notification Action</MessageCode>
        <FromRoleClass>PIP Failure Notifier</FromRoleClass>
        <FromService>Failure Notifier Service</FromService>
        <ToRoleClass>Failure Report Administrator</ToRoleClass>
        <ToService>Failure Report Administrator Service</ToService>
        <TransactionCode></TransactionCode>
        <NextAction></NextAction>
        <Indicator>0A1</Indicator>
        <ProcessCode>Notification of Failure</ProcessCode>
        <ProcessVersion>V02.00</ProcessVersion>
    </Message>

    <!-- 2A1 Product Resource Update 1.0 -->
    <Message>
        <MsgType>Pip2A1ProductResourceUpdate</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/Pip2A1ProductResourceUpdateGuideline.dtd</DTDfilename>
        <MessageCode>Product Resource Update Action</MessageCode>
        <FromRoleClass>Product Information Distributor</FromRoleClass>
        <FromService>Product Information Distributor Service</FromService>
        <ToRoleClass>Product Information User</ToRoleClass>
        <ToService>Product Information User Service</ToService>
        <TransactionCode>Distribute New Product Information</TransactionCode>
        <NextAction></NextAction>
        <Indicator>2A1</Indicator>
        <ProcessCode>Distribute New Product Information</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>

    <!-- 2A1 Product Information Notification 1.0 -->
    <Message>
        <MsgType>Pip2A1ProductInformationNotification</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/Pip2A1ProductInformationNotificationGuideline.dtd</DTDfilename>
        <MessageCode>Product Information Notification Action</MessageCode>
        <FromRoleClass>Product Information Distributor</FromRoleClass>
        <FromService>Product Information Distributor Service</FromService>
        <ToRoleClass>Buyer</ToRoleClass>
        <ToService>Buyer Service</ToService>
        <TransactionCode>Distribute New Product Information</TransactionCode>
        <NextAction></NextAction>
        <Indicator>2A1</Indicator>
        <ProcessCode>Distribute New Product Information</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>

    <!-- 2A2 Product Information Query 1.0 -->
    <Message>
        <MsgType>Pip2A2ProductInformationQuery</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/2A2ProductInformationQueryMessageGuideline.dtd</DTDfilename>
        <MessageCode>Product Information Query Action</MessageCode>
        <FromRoleClass>Product Information User</FromRoleClass>
        <FromService>Product Information User Service</FromService>
        <ToRoleClass>Product Information Distributor</ToRoleClass>
        <ToService>Product Information Distributor Service</ToService>
        <TransactionCode>Query Product Information</TransactionCode>
        <NextAction>Product Information Response Action</NextAction>
        <Indicator>2A2</Indicator>
        <ProcessCode>Query Product Information</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>

    <!-- 2A2 Product Information Response 1.0 -->
    <Message>
        <MsgType>Pip2A2ProductInformationResponse</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/2A2ProductInformationResponseMessageGuideline.dtd</DTDfilename>
        <MessageCode>Product Information Response Action</MessageCode>
        <FromRoleClass>Product Information Distributor</FromRoleClass>
        <FromService>Product Information Distributor Service</FromService>
        <ToRoleClass>Product Information User</ToRoleClass>
        <ToService>Product Information User Service</ToService>
        <TransactionCode>Query Product Information</TransactionCode>
        <NextAction></NextAction>
        <Indicator>2A2</Indicator>
        <ProcessCode>Query Product Information</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>

    <!-- 2A5 Technical Information Query 1.0 -->
    <Message>
        <MsgType>Pip2A5TechnicalInformationQuery</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/2A5TechnicalInformationQueryMessageGuideline.dtd</DTDfilename>
        <MessageCode>Technical Information Query Action</MessageCode>
        <FromRoleClass>Product Information User</FromRoleClass>
        <FromService>Product Information User Service</FromService>
        <ToRoleClass>Product Information Distributor</ToRoleClass>
        <ToService>Product Information Distributor Service</ToService>
        <TransactionCode>Query Technical Information</TransactionCode>
        <NextAction>Technical Information Response Action</NextAction>
        <Indicator>2A5</Indicator>
        <ProcessCode>Query Technical Information</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>

    <!-- 2A5 Technical Information Response 1.0 -->
    <Message>
        <MsgType>Pip2A5TechnicalInformationResponse</MsgType>
        <MessageVersion>1.0</MessageVersion>
        <DTDfilename>rosetta/2A5TechnicalInformationResponseMessageGuideline.dtd</DTDfilename>
        <MessageCode>Technical Information Response Action</MessageCode>
        <FromRoleClass>Product Information Distributor</FromRoleClass>
        <FromService>Product Information Distributor Service</FromService>
        <ToRoleClass>Product Information User</ToRoleClass>
        <ToService>Product Information User Service</ToService>
        <TransactionCode>Query Technical Information</TransactionCode>
        <NextAction></NextAction>
        <Indicator>2A5</Indicator>
        <ProcessCode>Query Technical Information</ProcessCode>
        <ProcessVersion>1.0</ProcessVersion>
    </Message>

    <!-- 2A9 EC Technical Information Query V01.00 -->
    <Message>
        <MsgType>Pip2A9ECTechnicalInformationQuery</MsgType>
