=== naota-inamoto/Altair/sample/server/dtd/PartnerInfo.dtd
<!ELEMENT PartnerInfo (Target, Id, BusinessId, MsgType, MyRole, PartnerRole, Properties*)>

<!ELEMENT Target (#PCDATA)>
<!ELEMENT Id     (#PCDATA)>

<!ELEMENT BusinessId  (#PCDATA)>
<!ELEMENT MsgType     (#PCDATA)>
<!ELEMENT MyRole      (#PCDATA)>
<!ELEMENT PartnerRole (#PCDATA)>

<!ELEMENT Properties (Name, Value)>
<!ELEMENT Name  (#PCDATA)>
<!ELEMENT Value (#PCDATA)>

=== naota-inamoto/Altair/sample/server/data/rosetta/init_partner_info_default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PartnerInfo SYSTEM "PartnerInfo.dtd">
<PartnerInfo>
    <Target>rosetta</Target>
    <Id>rosetta:-- default setting --</Id>
    <BusinessId></BusinessId>
    <MsgType></MsgType>
    <MyRole></MyRole>
    <PartnerRole>-- default setting --</PartnerRole>

    <Properties>
        <Name>retry.max</Name>
        <Value>4</Value>
    </Properties>
    <Properties>
        <Name>error.retry.max</Name>
        <Value>4</Value>
    </Properties>
    <Properties>
        <Name>error.retry.time</Name>
        <Value>5m</Value>
    </Properties>
    <Properties>
        <Name>receipt.wait.time</Name>
        <Value>2h</Value>
    </Properties>
    <Properties>
        <Name>reply.wait.time</Name>
        <Value>22h</Value>
    </Properties>


    <Properties>
        <Name>usage.code</Name>
        <Value>Product</Value>
    </Properties>
    <Properties>
        <Name>encoding</Name>
        <Value>binary</Value>
    </Properties>

    <!-- encryption -->
    <Properties>
        <Name>encryption.part</Name>
        <Value></Value>
    </Properties>
    <Properties>
        <Name>encryption.algorithm</Name>
        <Value>rc2-128</Value>
    </Properties>

    <!-- signature verify -->
    <Properties>
        <Name>ca.cert</Name>
        <Value>./keystore/ca/cert.pem</Value>
    </Properties>
    <Properties>
        <Name>receive.signature</Name>
        <Value>false</Value>
    </Properties>

    <!-- validation mode -->
    <Properties>
        <Name>validation.mode</Name>
        <Value>error</Value>
    </Properties>

    <!-- SSL -->
    <Properties>
        <Name>send.client.auth</Name>
        <Value>false</Value>
    </Properties>
</PartnerInfo>

=== naota-inamoto/Altair/sample/server/data/rosetta_sample/init_partner_info_supplier.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PartnerInfo SYSTEM "PartnerInfo.dtd">
<PartnerInfo>
    <Target>rosetta</Target>
    <Id>rosetta:SampleSupplier</Id>
    <BusinessId>000000000</BusinessId>
    <MsgType>*</MsgType>
    <MyRole>buyer</MyRole>
    <PartnerRole>supplier</PartnerRole>

    <Properties>
        <Name>URL</Name>
        <Value>http://localhost:8080/rosetta</Value>
    </Properties>

    <Properties>
        <Name>Class</Name>
        <Value>End User</Value>
    </Properties>
    <Properties>
        <Name>Supply Chain</Name>
        <Value>Information Technology</Value>
    </Properties>

    <!-- Business Process -->
    <Properties>
        <Name>Pip3A4PurchaseOrderAcceptance.process</Name>
        <Value>PoCompleteProcess</Value>
    </Properties>
    <Properties>
        <Name>Pip3A4PurchaseOrderRequest.sync</Name>
        <Value>false</Value>
    </Properties>

    <Properties>
        <Name>retry.max</Name>
        <Value>4</Value>
    </Properties>
    <Properties>
        <Name>error.retry.max</Name>
        <Value>4</Value>
    </Properties>
    <Properties>
        <Name>error.retry.time</Name>
        <Value>5m</Value>
    </Properties>
    <Properties>
        <Name>receipt.wait.time</Name>
        <Value>2h</Value>
    </Properties>
    <Properties>
        <Name>reply.wait.time</Name>
        <Value>22h</Value>
    </Properties>

    <Properties>
        <Name>usage.code</Name>
        <Value>Product</Value>
    </Properties>
    <Properties>
        <Name>encoding</Name>
        <Value>binary</Value>
    </Properties>

    <!-- encryption -->
    <Properties>
        <Name>encryption.part</Name>
        <Value></Value>
    </Properties>

    <!-- decryptyion, verification -->
    <Properties>
        <Name>cert</Name>
        <Value>./keystore/supplier/cert.pem</Value>
    </Properties>
    <Properties>
        <Name>ca.cert</Name>
        <Value>./keystore/ca/cert.pem</Value>
    </Properties>

    <!-- send signature -->
    <Properties>
        <Name>send.signature</Name>
        <Value>false</Value>
    </Properties>

    <!-- validation mode -->
    <Properties>
        <Name>validation.mode</Name>
        <Value>error</Value>
    </Properties>

    <!-- SSL -->
    <Properties>
        <Name>send.client.auth</Name>
        <Value>false</Value>
    </Properties>
    <Properties>
        <Name>receive.auth.host</Name>
        <Value></Value>
    </Properties>

    <Properties>
        <Name>receive.server.auth</Name>
        <Value>false</Value>
    </Properties>
    <Properties>
        <Name>server.auth.host</Name>
        <Value></Value>
    </Properties>
</PartnerInfo>
