=== naota-inamoto/Altair/sample/server/dtd/WebUiData.dtd
<!ELEMENT WebUiData (Target, MenuItem*)>

<!ELEMENT Target (#PCDATA)>

<!-- Menu -->
<!ELEMENT MenuItem (LineNumber, Name, Kind, Text, View?)>
    <!-- Kind:  "Title" | "View" -->

<!-- View -->
<!ELEMENT View (RoleName*, UiElem*)>
<!ELEMENT RoleName (#PCDATA)>

<!ELEMENT UiElem (LineNumber, Name, Kind, Text?, Selectable?)>

    <!-- Kind:  "Title" | "Text" |  "Link" | "BR" |
                "Button" | "Check" | "Radio"  | "TextField" | "TextArea" | "Password" | "Upload" |
                "Select" | "Table1" | "Table2" -->

<!ELEMENT Selectable (Children*, Condition2?, TableItem*)>

<!ELEMENT Children (LineNumber, ((MsgType, MsgVersion, DTDfilename) | ChildPath), Condition*, Type, Default?)>
<!ELEMENT MsgType     (#PCDATA)>
<!ELEMENT MsgVersion  (#PCDATA)>
<!ELEMENT DTDfilename (#PCDATA)>
<!ELEMENT ChildPath   (#PCDATA)>
<!ELEMENT Type        (#PCDATA)>
<!ELEMENT Default     (#PCDATA)>

    <!-- Type: single or multiple -->

<!ELEMENT Condition (LineNumber, Path, Value)>
<!ELEMENT Path  (#PCDATA)>
<!ELEMENT Value (#PCDATA)>

<!ELEMENT Condition2 (
    RangePath, RangeType, From, To,
    OrderByPath, OrderByType, Desc, CountFrom, CountMax,
    ColumnName, ColumnValue, ColumnName2, ColumnValue2)>
<!ELEMENT RangePath (#PCDATA)>
<!ELEMENT RangeType (#PCDATA)>
<!ELEMENT From (#PCDATA)>
<!ELEMENT To (#PCDATA)>
<!ELEMENT OrderByPath (#PCDATA)>
<!ELEMENT OrderByType (#PCDATA)>
<!ELEMENT Desc (#PCDATA)>
<!ELEMENT CountFrom (#PCDATA)>
<!ELEMENT CountMax  (#PCDATA)>
<!ELEMENT ColumnName  (#PCDATA)>
<!ELEMENT ColumnValue (#PCDATA)>
<!ELEMENT ColumnName2  (#PCDATA)>
<!ELEMENT ColumnValue2 (#PCDATA)>

<!ELEMENT TableItem (LineNumber, Path, Editable, Password?)>
<!ELEMENT Editable (#PCDATA)>
<!ELEMENT Password (#PCDATA)>

    <!-- MsgVersion, From, To, Value, CountFrom, CountMax:  xxxx fixed value,
                                                            @name variable,
                                                            #name session variable
                                                            name=default - TextField,
                                                            * - ignore
         RangeType, OrderByType: integer or string,
         Desc, Editable, Password: false or true      -->

<!-- Common -->
<!ELEMENT LineNumber (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Kind (#PCDATA)>
<!ELEMENT Text (#PCDATA)>

=== naota-inamoto/Altair/sample/server/data/bizsoft/sales/init_webuidata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WebUiData SYSTEM "WebUiData.dtd">
<WebUiData>
    <Target>bizsoftSales</Target>
    <MenuItem>
        <LineNumber>1000</LineNumber>
        <Name>PurchaseOrder</Name>
        <Kind>Title</Kind>
        <Text>íçï∂</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>1001</LineNumber>
        <Name>PurchaseOrder</Name>
        <Kind>View</Kind>
        <Text>íçï∂èë</Text>
        <View>
            <RoleName>sales</RoleName>
        </View>
    </MenuItem>

    <MenuItem>
        <LineNumber>2000</LineNumber>
        <Name>Inventory</Name>
        <Kind>Title</Kind>
        <Text>ç›å…</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>2001</LineNumber>
        <Name>Inventory</Name>
        <Kind>View</Kind>
        <Text>ç›å…</Text>
        <View>
            <RoleName>sales</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>2002</LineNumber>
        <Name>ProductArrival</Name>
        <Kind>View</Kind>
        <Text>ì¸â◊</Text>
        <View>
            <RoleName>sales</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>2003</LineNumber>
        <Name>Shipment</Name>
        <Kind>View</Kind>
        <Text>èoâ◊</Text>
        <View>
            <RoleName>sales</RoleName>
        </View>
    </MenuItem>
</WebUiData>

=== naota-inamoto/Altair/sample/server/data/rosetta_sample/init_supplier_webuidata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WebUiData SYSTEM "WebUiData.dtd">
<WebUiData>
    <Target>rosettaSampleSupplier</Target>
    <MenuItem>
        <LineNumber>1</LineNumber>
        <Name>Process</Name>
        <Kind>Title</Kind>
        <Text>Tasks</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>2</LineNumber>
        <Name>Receipt</Name>
        <Kind>View</Kind>
        <Text>Receipt</Text>
        <View>
            <RoleName>supplier</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>3</LineNumber>
        <Name>Inventory</Name>
        <Kind>View</Kind>
        <Text>Inventory</Text>
        <View>
            <RoleName>supplier</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>4</LineNumber>
        <Name>Fulfill</Name>
        <Kind>View</Kind>
        <Text>Fulfill</Text>
        <View>
            <RoleName>supplier</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>5</LineNumber>
        <Name>Invoice</Name>
        <Kind>View</Kind>
        <Text>Invoice</Text>
        <View>
            <RoleName>supplier</RoleName>
        </View>
    </MenuItem>
</WebUiData>

=== naota-inamoto/Altair/sample/server/data/bizsoft/customer/init_webuidata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WebUiData SYSTEM "WebUiData.dtd">
<WebUiData>
    <Target>bizsoftCustomer</Target>
    <MenuItem>
        <LineNumber>1000</LineNumber>
        <Name>MyAccount</Name>
        <Kind>Title</Kind>
        <Text>マイアカウント</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>1001</LineNumber>
        <Name>MyAccount</Name>
        <Kind>View</Kind>
        <Text>登録情報</Text>
        <View>
            <RoleName>customer</RoleName>
        </View>
    </MenuItem>

    <MenuItem>
        <LineNumber>2000</LineNumber>
        <Name>PurchaseOrder</Name>
        <Kind>Title</Kind>
        <Text>注文</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>2001</LineNumber>
        <Name>Cart</Name>
        <Kind>View</Kind>
        <Text>カート</Text>
        <View>
            <RoleName>customer</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>2002</LineNumber>
        <Name>ProductList</Name>
        <Kind>View</Kind>
        <Text>製品一覧</Text>
        <View>
            <RoleName>customer</RoleName>
        </View>
    </MenuItem>
</WebUiData>

=== naota-inamoto/Altair/sample/server/data/bizsoft/finance/init_webuidata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WebUiData SYSTEM "WebUiData.dtd">
<WebUiData>
    <Target>bizsoftAccount</Target>
    <MenuItem>
        <LineNumber>1000</LineNumber>
        <Name>Check</Name>
        <Kind>Title</Kind>
        <Text>“`•[</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>1001</LineNumber>
        <Name>CheckList</Name>
        <Kind>View</Kind>
        <Text>“`•[ˆê——</Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>1002</LineNumber>
        <Name>CheckInput</Name>
        <Kind>View</Kind>
        <Text>“`•[“ü—Í</Text>
        <View>
            <RoleName>account</RoleName>
            <UiElem>
                <LineNumber>10</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>U‘Ö“`•[“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>11</LineNumber>
                <Name>BR</Name>
                <Kind>BR</Kind>
            </UiElem>
            <UiElem>
                <LineNumber>20</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>“ü‹à“`•[“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>21</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>o‹à“`•[“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>22</LineNumber>
                <Name>BR</Name>
                <Kind>BR</Kind>
            </UiElem>
            <UiElem>
                <LineNumber>23</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>”„ã“`•[“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>24</LineNumber>
                <Name>BR</Name>
                <Kind>BR</Kind>
            </UiElem>
            <UiElem>
                <LineNumber>25</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>¤•id“ü“`•[“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>26</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>Ş—¿d“ü“`•[“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>27</LineNumber>
                <Name>BR</Name>
                <Kind>BR</Kind>
            </UiElem>
            <UiElem>
                <LineNumber>28</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>‰c‹ÆŒo”ï“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>29</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>»‘¢Œo”ï“ü—Í</Text>
            </UiElem>
            <UiElem>
                <LineNumber>30</LineNumber>
                <Name>BR</Name>
                <Kind>BR</Kind>
            </UiElem>
            <UiElem>
                <LineNumber>31</LineNumber>
                <Name>submit</Name>
                <Kind>Button</Kind>
                <Text>İ”õw“ü</Text>
            </UiElem>
            <UiElem>
                <LineNumber>32</LineNumber>
                <Name>BR</Name>
                <Kind>BR</Kind>
            </UiElem>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>1003</LineNumber>
        <Name>CheckCheck</Name>
        <Kind>View</Kind>
        <Text>“`•[ƒ`ƒFƒbƒN</Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>

    <MenuItem>
        <LineNumber>2000</LineNumber>
        <Name>Ledger</Name>
        <Kind>Title</Kind>
        <Text>Œ³’ </Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>2001</LineNumber>
        <Name>Ledger</Name>
        <Kind>View</Kind>
        <Text>Œ³’ </Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>

    <MenuItem>
        <LineNumber>3000</LineNumber>
        <Name>FinancialStatement</Name>
        <Kind>Title</Kind>
        <Text>à–±”•\</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>3001</LineNumber>
        <Name>BalanceSheet</Name>
        <Kind>View</Kind>
        <Text>‘İØ‘ÎÆ•\</Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>3002</LineNumber>
        <Name>EarningStatement</Name>
        <Kind>View</Kind>
        <Text>‘¹‰vŒvZ‘</Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>
    <MenuItem>
        <LineNumber>3003</LineNumber>
        <Name>TrialBalanceSheet</Name>
        <Kind>View</Kind>
        <Text>Z•\</Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>

    <MenuItem>
        <LineNumber>4000</LineNumber>
        <Name>Setting</Name>
        <Kind>Title</Kind>
        <Text>İ’è</Text>
    </MenuItem>
    <MenuItem>
        <LineNumber>4001</LineNumber>
        <Name>AccountHeadings</Name>
        <Kind>View</Kind>
        <Text>Š¨’è‰È–Ú</Text>
        <View>
            <RoleName>account</RoleName>
        </View>
    </MenuItem>
</WebUiData>
